//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eQuiz.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SettlementEntities : DbContext
    {
        public SettlementEntities()
            : base("name=SettlementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblBenefit> tblBenefit { get; set; }
        public virtual DbSet<tblHostel> tblHostel { get; set; }
        public virtual DbSet<tblPayment> tblPayment { get; set; }
        public virtual DbSet<tblResidence> tblResidence { get; set; }
        public virtual DbSet<tblRoles> tblRoles { get; set; }
        public virtual DbSet<tblRoom> tblRoom { get; set; }
        public virtual DbSet<tblRoomType> tblRoomType { get; set; }
        public virtual DbSet<tblStudent> tblStudent { get; set; }
        public virtual DbSet<tblStudentBenefit> tblStudentBenefit { get; set; }
        public virtual DbSet<tblStudentResidence> tblStudentResidence { get; set; }
        public virtual DbSet<tblStudentRoom> tblStudentRoom { get; set; }
        public virtual DbSet<tblStudentViolation> tblStudentViolation { get; set; }
        public virtual DbSet<tblUsers> tblUsers { get; set; }
        public virtual DbSet<tblViolation> tblViolation { get; set; }
        public virtual DbSet<tblSettleRequest> tblSettleRequest { get; set; }
    }
}
