//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eQuiz.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPayment
    {
        public int Id { get; set; }
        public int StudentId { get; set; }
        public int HostelId { get; set; }
        public int Amount { get; set; }
        public System.DateTime PaymentDate { get; set; }
    
        public virtual tblHostel tblHostel { get; set; }
        public virtual tblStudent tblStudent { get; set; }
    }
}
